accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('your_profile/<int:pk>/', views.YourProfileView.as_view(), name='your_profile'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path("password/set/", views.PasswordSetView.as_view(), name="account_set_password"),
    path("password/change/", views.PasswordChangeView.as_view(), name="account_change_password"),
    path("withdrawal/", views.WithdrawalView.as_view(), name="withdrawal"),
    path("withdrawal_done/", views.WithdrawalDoneView.as_view(), name="withdrawal_done"),
    path("reregistration/", views.ReRegistrationView.as_view(), name="reregistration"),
    path('follow_user/<int:pk>/', views.follow_user, name='follow_user'),
    path('unfollow_user/<int:pk>/', views.unfollow_user, name='unfollow_user'),
    path('followers/<int:pk>/', views.follows, name='followers'),
    path('follows/<int:pk>/', views.follows, name='follows'),
]

app/urls.py
from django.urls import path

from app import views

app_name = 'app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('tip_create/', views.TipCreateView.as_view(), name='tip_create'),
    path('tip_detail/<int:pk>/', views.TipDetailView.as_view(), name='tip_detail'),
    path('tip_update/<int:pk>/', views.TipUpdateView.as_view(), name='tip_update'),
    path('tip_delete/<int:pk>/', views.TipDeleteView.as_view(), name='tip_delete'),
    path('tip_list/', views.TipMyListView.as_view(), name='tip_list'),
    path('tip_public_list/', views.TipPublicListView.as_view(), name='tip_public_list'),
    path('add_comment/<int:pk>/', views.add_comment, name='add_comment'),
    path('delete_comment/<int:pk>/<int:comment_no>/', views.delete_comment, name='delete_comment'),
    path('add_like/<int:pk>/', views.add_like, name='add_like'),
    path('delete_like/<int:pk>/', views.delete_like, name='delete_like'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('notifications/', views.notifications, name='notifications'),
    path('terms/', views.TermsView.as_view(), name='terms'),
    path('policy/', views.PolicyView.as_view(), name='policy'),
    path('usertip/<int:id>/', views.UserTipView.as_view(), name='usertip'),
]

templates/app/contact.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}お問い合わせ{% endblock %}

{% block content %}

    <div class="card card-profile my-5 mx-auto">
        <div class="card-body">
            <div class="card-title text-center">お問い合わせ</div>
            <form method="post" onsubmit="return false;">
                {% csrf_token %}
                <table class="profile_table mb-4">
                    <tbody>
                        <tr>
                            <th class="header">{{ form.name.label }}</th>
                            <td class="data">
                                {% render_field form.name class="form-control" placeholder='' %}
                                {% for error in form.name.errors %}
                                    <p class="text-danger">{{ error }}</p>
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <th class="header">{{ form.email.label }}</th>
                            <td class="data">
                                {% render_field form.email class="form-control" placeholder='' %}
                                {% for error in form.email.errors %}
                                    <p class="text-danger">{{ error }}</p>
                                {% endfor %}
                            </td>
                        </tr>
                        <tr>
                            <th class="header">{{ form.message.label }}</th>
                            <td class="data">
                                {% render_field form.message class="form-control" placeholder='' %}
                                {% for error in form.message.errors %}
                                    <p class="text-danger">{{ error }}</p>
                                {% endfor %}
                            </td>
                        </tr>
                    </tbody>
                </table>
                {# non_field_errorを表示 #}
                {% include 'form_alert.html' %}
                <div class="button mx-auto text-center my-2">
                    <button class="btn btn-custom btn-lg btn-warning btn-block" type="button" onclick="submit();">
                        <i class="fas fa-paper-plane">&nbsp;送信する</i>
                    </button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/app/index.html
{% extends 'base.html' %}
{% load static %}

{% block extra_css%}
    <link rel="stylesheet" href="{% static 'app/css/home.css' %}">
{% endblock %}

{% block title %}TipStock{% endblock %}

{% block content %}
    {% if user.is_superuser %}
        {% if maintenance_mode %}
            <a href="{% url 'maintenance_mode_off' %}">メンテナンス終了</a>
        {% else %}
            <a href="{% url 'maintenance_mode_on' %}">メンテナンス開始</a>
        {% endif %}
    {% endif %}

    <section class="top">
        <div>
            <p class="top-title">
                TipStock
            </p>
            <p class="top-subtitle">
                コードをTipに保存して<br>すぐ見つけ出せるようにしよう！<br>
                <small>(改善点・要望はお問い合わせから)</small>
            </p>
        </div>
    </section>

    <section class="about section">
        <div class="clear">
            <h2 class="section-title">TipStockとは</h2>
            <div class="about-left">
                <img src="{% static 'app/img/about.png' %}" alt="TipStockとは">
            </div>
            <div class="about-right">
                <p>「TipStock」はコードをTipとして保存しておくことで、後からいつでも確認できるシンプルなサービスです。</p>
                <p>コーディングしている時、「ここのコードどう書くんだったっけ？」のような、書いたことはあるけど思い出せないようなことはありませんか。
                    その際、参考書やWeb検索などで調べるわけですが、たった数行でも意外と時間がかかったりします。
                    コードを見ればこれだ！とわかるのに、そのコードになかなか辿りつけない。これは、コード以外の情報量が多いからだと感じました。</p>
                <p>そこで、ある程度「コード」に特化した情報だけを保存しておき、いつでも確認できるようにしておけば便利なのでは思い、本サービスを開発しました。
                    本サービスは本当にちょっとしたコードを対象にし、基本的には個人が見返すための利用を考えています。
                    ただ、情報共有することは私を含めた困っている人達の大きな手助けとなるため、保存したTipは公開(*)を前提としています。</p>
                <p>TipをどんどんStockして効率的に開発をしていきましょう。</p>
                <p><small>(*)Tip毎に公開・非公開を選択できますが、公開を推奨したいため非公開の保存数を制限しています。({{ private_tips_maxnum }}個)</small>
                </p>
            </div>
        </div>
    </section>
    <section class="menu section">
        <div class="container">
            <h2 class="section-title">使用方法</h2>
            <div class="menu-wrapper">
                <div class="menu-item">
                    <h5 class="menu-title">
                        <strong>Tip Form</strong><br>
                        <div class="text-danger fs-6">（ユーザ登録必要）</div>
                    </h5>
                    <p>
                        Tip FormからTip(コード)を登録します。特定のファイルに対するコードを登録できるよう、ファイル名とコードをセットで入力することができます。<br>
                        ファイル名(拡張子)から言語を特定することで、コードが言語に応じたハイライト表示となります。
                    </p>
                </div>
                <div class="menu-item">
                    <h5 class="menu-title">
                        <strong>My Tips</strong><br>
                        <div class="text-danger fs-6">（ユーザ登録必要）</div>
                    </h5>
                    <p>
                        My Tipsでは自身が登録したTipの一覧を検索・確認することができ、各Tipを選択することで登録内容の確認・更新・削除を実施することができます。<br>
                        Public TipsからTipをお気に入り登録すると、My Tipでも表示されるようになります。
                    </p>
                </div>
                <div class="menu-item">
                    <h5 class="menu-title">
                        <strong>Public Tips</strong><br>
                        <div class="fs-6">（ユーザ登録不要）</div>
                    </h5>
                    <p>
                        Public Tipsでは、Tipの公開範囲がPublicとなっているTipの一覧が表示され、他の人が投稿したTipも検索・確認することができます。<br>
                        Tipに対してお気に入り登録やコメント投稿をすることができます。
                    </p>
                </div>
            </div>
            <h5 class="menu-title">
                <strong>その他</strong>
            </h5>
            <ul>
                <li>
                    ユーザのプロフィール画面よりユーザ名、アイコン、パスワードの変更が可能となります（メールアドレスの変更は不可）。また、投稿数やフォロワー等のデータも確認できます。
                </li>
                <li>
                    お気に入り登録はTip FormよりTipを２つ以上登録しないと実行できません。
                </li>
                <li>
                    Tipの画面の登録者をクリックするとそのユーザのTips(Public)が表示され、「プロフィールへ」ボタンからプロフィールの参照、フォローをすることができます。
                </li>
                <li>
                    現状フォロー機能は自身のプロフィールからフォロー、フォロワーを参照できるのみです。今後、フォローユーザがTipを登録するとお知らせが届くなどの機能も。
                </li>
                <li>
                    お知らせはコメントの宛先、フォローした相手にその旨が届きます(リアルタイムではなくページロード時に更新、件数表示で30日経過で削除予定)。
                </li>
            </ul>
        </div>
    </section>
    <section class="note section">
        <div>
            <h2 class="section-title">注意事項</h2>
            <p class="note-message">本サービスはWeb開発初心者が勢いと努力で作成しております。</p>
            <p class="note-message">そのため、不具合等でサービスが利用できない状況に陥ることも十分考えられます。</p>
            <p class="note-message">その点ご留意の上、ご利用頂ければ幸いです。</p>
            <p class="note-message">ご利用時は、<a href="{% url 'app:terms' %}">利用規約</a>
                及び
                <a href="{% url 'app:policy' %}">プライバシーポリシー</a>
                に同意したこととさせて頂きます。</p>
            <p class="note-message">不備等ご連絡頂ければ非常に助かります。</p>
        </div>
    </section>
    <section class="register section">
        <div class="container">
            <h2 class="section-title">ユーザ登録</h2>
            <p class="register-message">Tipの登録等はユーザ登録が必要です。</p>
            <a href="{% url 'accounts:signup' %}" class="btn-register">ユーザ登録画面へ</a>
        </div>
    </section>

{% endblock %}

templates/app/notifications.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% load query %}

{% block title %}お知らせ{% endblock %}

{% block content %}
    <h2 class="my-3 me-3">お知らせ</h2>
    <div class="d-inline-flex mb-3">
        <form action="{% url 'app:notifications' %}" method="get">
            <button type="submit" name="display" value="unread" class="btn btn-custom btn-outline-success">未確認のみ</button>
            <button type="submit" name="display" value="all" class="btn btn-custom btn-outline-secondary">全て</button>
        </form>
        <form action="{% url 'app:notifications' %}" method="get" class="ms-4" id="all-read">
            <button type="button" class="btn btn-custom btn-warning" id="read-button">全て確認済にする</button>
            <input type="hidden" name="allRead" value="done">
            <input type="hidden" name="display" value="{{ request.build_absolute_uri|get_query:'display' }}">
        </form>
    </div>
    {% if not notifications %}
        <p>新しいお知らせはありません。</p>
    {% endif %}

    {% for notification in notifications %}
        <div
            class="card my-4 {% if notification.is_read %}already-read{% endif %}"
            style="max-width: 800px;">
            <div class="row">
                <div class="col-3 col-md-2 px-0 d-flex align-items-center justify-content-center">
                    {% if notification.category == 'event' %}
                        <img src="{% static 'app/img/event.png' %}" class="notification-icon">
                    {% else %}
                        <img
                            src="
                            {% if notification.created_by.icon %}
                                {{ notification.created_by.icon.url }}
                            {% else %}
                                {% static 'accounts/img/noimage.png' %}
                            {% endif %}"
                            class="notification-icon">
                    {% endif %}
                </div>
                <div class="col-9 col-md-10 px-0">
                    <div class="card-body notification-body">
                        <p class="card-text">
                            {% if notification.category == 'comment' %}
                                <a href="{% url 'app:notifications' %}?goto=comment&notification={{ notification.pk }}">
                                    <strong>
                                        {% if notification.created_by.is_active %}
                                            {{ notification.created_by.username }}
                                        {% else %}
                                            Inactive User
                                        {% endif %}
                                    </strong>
                                    さんがあなたの「{{ notification.tip.title|truncatechars:15 }}」にコメントしました。
                                </a>
                                <br>
                                <small class="text-muted">受信:{{ notification.created_at|naturaltime }}</small>
                                {% if notification.is_read %}
                                    <small class="text-dark">確認済</small>
                                {% else %}
                                    <small class="text-danger">未確認</small>
                                {% endif %}
                            {% elif notification.category == 'event' %}
                                <a href="{% url 'app:notifications' %}?goto=event&notification={{ notification.pk }}">
                                    「{{ notification.tip.title|truncatechars:15 }}」が<strong>{{ notification.content }}</strong>
                                </a>
                                <br>
                                <small class="text-muted">{{ notification.created_at|naturaltime }}</small>
                                {% if notification.is_read %}
                                    <small class="text-dark">確認済</small>
                                {% else %}
                                    <small class="text-danger">未確認</small>
                                {% endif %}
                            {% elif notification.category == 'follow' %}
                                <a href="{% url 'app:notifications' %}?goto=follow&notification={{ notification.pk }}">
                                    <strong>
                                        {% if notification.created_by.is_active %}
                                            {{ notification.created_by.username }}
                                        {% else %}
                                            Inactive User
                                        {% endif %}
                                    </strong>
                                    さんがあなたをフォローしました。
                                </a>
                                <br>
                                <small class="text-muted">受信:{{ notification.created_at|naturaltime }}</small>
                                {% if notification.is_read %}
                                    <small class="text-dark">確認済</small>
                                {% else %}
                                    <small class="text-danger">未確認</small>
                                {% endif %}
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

{% block extra_js %}
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        $(function () {
            // 全て既読ボタンクリック時のダイアログ表示
            $("#read-button").click(function () {
                swal("全て既読にしてもよろしいですか？", {
                    icon: 'warning',
                    buttons: {
                        yes: "はい",
                        cancel: "キャンセル"
                    }
                }).then((value) => {
                    switch (value) {

                        case "yes":
                            $('#all-read').submit();
                            break;

                        default:
                            break;
                    }
                });
            })
        });
    </script>

{% endblock %}

templates/app/pagenation.html
<div class="pagination mt-3">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; 最初へ</a>
            <a href="?page={{ page_obj.previous_page_number }}">前へ</a>
        {% endif %}

        <span class="current">
            Page
            {{ page_obj.number }}
            of
            {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">次へ</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">最後へ &raquo;</a>
        {% endif %}
    </span>
</div>

templates/app/policy.html
{% extends 'base.html' %}

{% block title %}プライバシーポリシー{% endblock %}

{% block content %}

    <div class="my-5">
        <h3 class="mb-3 fw-bold">プライバシーポリシー</h3>
        <p>
            このプライベートポリシー(以下、「本ポリシー」といいます。)は，このウェブサイト上で提供するサービス（以下，「本サービス」といいます。）における，ユーザーの個人情報の取り扱いについて定めるものです。登録ユーザーの皆さま（以下，「ユーザー」といいます。）には本ポリシーに従って，本サービスをご利用いただきます。
            <br>
            ユーザーは本サービスに利用登録することにより，本ポリシーの全ての記載内容について同意したものとみなされます。
    </p>
    </div>
    <div class="mb-4">
        <h5 class="mb-3 fw-bold">第1条（個人情報の定義）</h5>
        <p>
            「個人情報」とは，個人情報の保護に関する法律に規定される生存する個人に関する情報(氏名、生年月日、その他の特定の個人を識別することができる情報)、ならびに特定の個人と結びついて使用されるメールアドレス、パスワードなどの情報と認識しています。
        </p>
    </div>
    <div class="mb-4">
        <h5 class="mb-3 fw-bold">第2条（クッキー・IPアドレス情報）</h5>
        <p>
            クッキーおよびＩＰアドレス情報(以下、クッキー等)については、それら単独では、特定の個人を識別することができないため、個人情報とは考えておりません。本サービスではプロフィールページへのログインの際や、本サービス上での全体傾向やパターンなどの情報を収集などにクッキーを使用しておりますが、ユーザーのプライバシーを侵害するものではありません。
            Googleを含む第三者配信事業者は、ファーストパーティ Cookie（Googleアナリティクスの Cookieなど）を 本サービスを訪れたユーザーの属性・興味・関心の分析に利用しております。
        </p>
    </div>
    <div class="mb-4">
        <h5 class="mb-3 fw-bold">第3条（個人情報の利用目的）</h5>
        <p class="mb-3">本サービスが個人情報を収集・利用する目的は，以下のとおりです</p>
        <ol>
            <li class="mb-3">
                本サービスの提供・運営のため
            </li>
            <li class="mb-3">
                ユーザーからのお問い合わせに回答するため（本人確認を行うことを含む）
            </li>
            <li class="mb-3">
                利用規約に違反したユーザーや，不正・不当な目的でサービスを利用しようとするユーザーの特定をし，ご利用をお断りするため
            </li>
            <li>
                ユーザーにご自身の登録情報の閲覧や変更，削除，ご利用状況の閲覧を行っていただくため
            </li>
        </ol>
    </div>
    <div class="mb-4">
        <h5 class="mb-3 fw-bold">第4条（利用目的の変更）</h5>
        <ol>
            <li class="mb-3">
                当社は，利用目的が変更前と関連性を有すると合理的に認められる場合に限り，個人情報の利用目的を変更するものとします。
            </li>
            <li>
                利用目的の変更を行った場合には，変更後の目的について当社所定の方法により，ユーザーに通知，または公表するものとします。
            </li>
        </ol>
    </div>
    <div class="mb-4">
        <h5 class="mb-3 fw-bold">第5条（個人情報の第三者提供）</h5>
        <ol>
            <li class="mb-3">
                本サービスは，次に掲げる場合を除くほか，あらかじめご本人の同意を得ないで、個人情報を第三者に提供しません。なお、本サービスは、メールアドレスなど直接特定の個人を識別することができる情報を除外した統計情報を第三者に開示する場合があります。
                <ol>
                    <li class="my-3">
                        人の生命，身体または財産の保護のために必要がある場合であって，本人の同意を得ることが困難であるとき
                    </li>
                    <li class="mb-3">
                        公衆衛生の向上または児童の健全な育成の推進のために特に必要がある場合であって，本人の同意を得ることが困難であるとき
                    </li>
                    <li class="mb-3">
                        国の機関もしくは地方公共団体またはその委託を受けた者が法令の定める事務を遂行することに対して協力する必要がある場合であって，本人の同意を得ることにより当該事務の遂行に支障を及ぼすおそれがあるとき
                    </li>
                    <li>
                        ユーザーが本サービスにおいて他のユーザーを含む第三者に表示する目的で当社に提供した情報（登録情報、投稿情報など）を本サービス上に表示する場合
                    </li>
                </ol>
            </li>
            <li class="mb-3">
                前項の定めにかかわらず，次に掲げる場合には，当該情報の提供先は第三者に該当しないものとします。
                <ol>
                    <li class="my-3">
                        本サービスが利用目的の達成に必要な範囲内において個人情報の取扱いの全部または一部を委託する場合
                    </li>
                    <li>
                        合併その他の事由による事業の承継に伴って個人情報が提供される場合
                    </li>
                </ol>
            </li>
        </ol>
    </div>
    <div class="mb-4">
        <h5 class="mb-3 fw-bold">第6条（個人情報の開示）</h5>
        <ol>
            <li class="mb-3">
                本サービスは，本人から個人情報の開示を求められたときは，本人に対し，遅滞なくこれを開示します。ただし，開示することにより次のいずれかに該当する場合は，その全部または一部を開示しないこともあり，開示しない決定をした場合には，その旨を遅滞なく通知します。
                <ol>
                    <li class="my-3">
                        本人または第三者の生命，身体，財産その他の権利利益を害するおそれがある場合
                    </li>
                    <li class="mb-3">
                        本サービスの適正な実施に著しい支障を及ぼすおそれがある場合
                    </li>
                    <li>
                        その他法令に違反することとなる場合
                    </li>
                </ol>
            </li>
            <li>
                前項の定めにかかわらず，履歴情報および特性情報などの個人情報以外の情報については，原則として開示いたしません。
            </li>
        </ol>
    </div>
    <div class="mb-4">
        <h5 class="mb-3 fw-bold">第7条（個人情報の訂正および削除）</h5>
        <ol>
            <li class="mb-3">
                ユーザーは，本サービスの保有する自己の個人情報が誤った情報である場合には，本サービスが定める手続きにより，本サービスに対して個人情報の訂正，追加または削除（以下，「訂正等」といいます。）を請求することができます。
            </li>
            <li class="mb-3">
                本サービスは，ユーザーから前項の請求を受けてその請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の訂正等を行うものとします。
            </li>
            <li>
                本サービスは，前項の規定に基づき訂正等を行った場合，または訂正等を行わない旨の決定をしたときは遅滞なく，これをユーザーに通知します。
            </li>
        </ol>
    </div>
    <div class="mb-4">
        <h5 class="mb-3 fw-bold">第8条（個人情報の利用停止等）</h5>
        <ol>
            <li class="mb-3">
                本サービスは，本人から，個人情報が，利用目的の範囲を超えて取り扱われているという理由，または不正の手段により取得されたものであるという理由により，その利用の停止または消去（以下，「利用停止等」といいます。）を求められた場合には，遅滞なく必要な調査を行います。
            </li>
            <li class="mb-3">
                前項の調査結果に基づき，その請求に応じる必要があると判断した場合には，遅滞なく，当該個人情報の利用停止等を行います。
            </li>
            <li class="mb-3">
                本サービスは，前項の規定に基づき利用停止等を行った場合，または利用停止等を行わない旨の決定をしたときは，遅滞なく，これをユーザーに通知します。
            </li>
            <li>
                前2項にかかわらず，利用停止等に多額の費用を有する場合その他利用停止等を行うことが困難な場合であって，ユーザーの権利利益を保護するために必要なこれに代わるべき措置をとれる場合は，この代替策を講じるものとします。
            </li>
        </ol>
    </div>
    <div class="mb-4">
        <h5 class="mb-3 fw-bold">第9条（プライバシーポリシーの変更）</h5>
        <ol>
            <li class="mb-3">
                本ポリシーの内容は，法令その他本ポリシーに別段の定めのある事項を除いて，ユーザーに通知することなく，変更することができるものとします。
            </li>
            <li>
                変更後のプライバシーポリシーは，本ウェブサイトに掲載したときから効力を生じるものとします。
            </li>
        </ol>
    </div>

{% endblock %}

templates/app/thanks.html
{% extends "base.html" %}

{% block title %}お問い合わせ{% endblock %}

{% block content %}

    <div class="card card-profile my-5 mx-auto">
        <div class="card-body">
            <div class="card-title text-center">お問い合わせありがとうございました。</div>
            <div class="text-center">
                <p class="mb-2">内容を確認いたしまして、ご連絡させて頂きます。</p>
                <p class="mb-4">しばらくお待ち下さい。</p>
                <a href="/" class="btn btn-custom btn-warning">ホームに戻る</a>
            </div>
        </div>
    </div>

{% endblock %}

templates/app/usertip.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}

{% block title %}{{ tip_user.username }}さんのTips{% endblock %}

{% block content %}
    <h2 class="my-3" style="word-break: break-word;">
        {% if tip_user.icon %}
            <img src="{{ tip_user.icon.url }}" class="icon-userpage">
        {% endif %}
        <span class="me-3">{{ tip_user.username }}さんのTips</span>
        <a href="{% url 'accounts:your_profile' tip_user.pk %}" class="btn btn-sm btn-info">プロフィールへ</a>
    </h2>
    <form method="get" name="searchForm">
        <div class="mb-3">
            <div class="mb-2 d-md-flex align-items-center">
                <label>検索内容：</label>
                <div class="form-group d-flex">
                    <div class="me-2">
                        <input
                            type="search"
                            value="{{ request.GET.query }}"
                            name="query"
                            class="query-search form-control"
                            placeholder="タイトルor説明orコード">
                        <input
                            type="search"
                            value="{{ request.GET.tagQuery }}"
                            name="tagQuery"
                            placeholder="タグ"
                            class="tag-search form-control">
                    </div>
                    <button type="submit" class="btn btn-sm btn-outline-primary">Search</button>
                </div>
            </div>
            <div class="mb-2">
                <label>表示順(降順)：</label>
                <div class="display-order">
                    <div class="btn-group btn-group-sm" role="group">
                        <input
                            type="radio"
                            class="btn-check"
                            name="displayOrder"
                            id="displayOrder1"
                            autocomplete="off"
                            value="updated"
                            {% if request.GET.displayOrder != 'liked' %}
                            checked="checked"
                            {% endif %}>
                        <label class="btn btn-outline-secondary" for="displayOrder1">更新日時</label>
                        <input
                            type="radio"
                            class="btn-check"
                            name="displayOrder"
                            id="displayOrder2"
                            autocomplete="off"
                            value="liked"
                            {% if request.GET.displayOrder == 'liked' %}
                            checked="checked"
                            {% endif %}>
                        <label class="btn btn-outline-secondary" for="displayOrder2">お気に入り数</label>
                    </div>
                </div>
            </div>
        </div>
    </form>
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-3">
        {% for tip in object_list %}
            <div class="col">
                <div class="card h-80 card-effect">
                    <div class="card-header">
                        {% for tag in tip.tags.all|slice:":3" %}
                            {% if forloop.counter == 3%}
                                <small>...</small>
                            {% else %}
                                <span class="tag">{{ tag|truncatechars:10 }}</span>
                            {% endif %}
                        {% endfor %}
                    </div>
                    <div class="card-body p-3">
                        <div class="card-text">
                            <p class="mb-1">
                                <strong>{{ tip.title|truncatechars:15 }}</strong>
                            </p>
                            <p class="mb-1">
                                <small>{{ tip.description|truncatechars:50 }}</small>
                            </p>
                        </div>
                        <a href="{{ tip.get_absolute_url }}" class="stretched-link"></a>
                    </div>
                    <div class="card-footer text-muted text-center">
                        <small>by&nbsp;
                            {% if tip.created_by.icon %}
                                <img src="{{ tip.created_by.icon.url }}" class="icon-display">
                            {% endif %}
                            {% if tip.created_by.is_active %}
                                {{ tip.created_by.username|truncatechars:20 }}
                            {% else %}
                                Inactive User
                            {% endif %}
                            <br>at&nbsp;{{ tip.updated_at|date:"Y/m/d" }}&nbsp;
                            {% if tip.public_set == 'private' %}
                                <span class="text-danger">Private</span>
                            {% else %}
                                <i class="fas fa-heart" style="color: pink;"></i>&nbsp;{{ tip.like_count }}
                            {% endif %}
                        </small>
                    </div>
                </div>
            </div>

            {% empty %}
            <h3>投稿がありません</h3>
        {% endfor %}
    </div>
    {# ページネーションを表示 #}
    {% include 'app/pagenation.html' %}
    <br>

{% endblock %}

{% block extra_js %}
    <script>
        $(function () {
            // 検索フォームの表示順・検索対象内のいずれかのボタンがクリックされたらsubmit
            $(document).on('change', '.btn-group', function (e) {
                document
                    .searchForm
                    .submit();
            });
        });
    </script>

{% endblock %}