accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('your_profile/<int:pk>/', views.YourProfileView.as_view(), name='your_profile'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path("password/set/", views.PasswordSetView.as_view(), name="account_set_password"),
    path("password/change/", views.PasswordChangeView.as_view(), name="account_change_password"),
    path("withdrawal/", views.WithdrawalView.as_view(), name="withdrawal"),
    path("withdrawal_done/", views.WithdrawalDoneView.as_view(), name="withdrawal_done"),
    path("reregistration/", views.ReRegistrationView.as_view(), name="reregistration"),
    path('follow_user/<int:pk>/', views.follow_user, name='follow_user'),
    path('unfollow_user/<int:pk>/', views.unfollow_user, name='unfollow_user'),
    path('followers/<int:pk>/', views.follows, name='followers'),
    path('follows/<int:pk>/', views.follows, name='follows'),
]

app/urls.py
from django.urls import path

from app import views

app_name = 'app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('tip_create/', views.TipCreateView.as_view(), name='tip_create'),
    path('tip_detail/<int:pk>/', views.TipDetailView.as_view(), name='tip_detail'),
    path('tip_update/<int:pk>/', views.TipUpdateView.as_view(), name='tip_update'),
    path('tip_delete/<int:pk>/', views.TipDeleteView.as_view(), name='tip_delete'),
    path('tip_list/', views.TipMyListView.as_view(), name='tip_list'),
    path('tip_public_list/', views.TipPublicListView.as_view(), name='tip_public_list'),
    path('add_comment/<int:pk>/', views.add_comment, name='add_comment'),
    path('delete_comment/<int:pk>/<int:comment_no>/', views.delete_comment, name='delete_comment'),
    path('add_like/<int:pk>/', views.add_like, name='add_like'),
    path('delete_like/<int:pk>/', views.delete_like, name='delete_like'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('notifications/', views.notifications, name='notifications'),
    path('terms/', views.TermsView.as_view(), name='terms'),
    path('policy/', views.PolicyView.as_view(), name='policy'),
    path('usertip/<int:id>/', views.UserTipView.as_view(), name='usertip'),
]

accounts/forms.py
from django import forms
from django.contrib.auth import get_user_model

from .widgets import FileInputWithPreview


class ProfileForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('username', 'icon', 'self_introduction')
        widgets = {
            'icon': FileInputWithPreview(),
            'self_introduction': forms.Textarea(attrs={'rows': 4}),
        }


class WithdrawalForm(forms.Form):
    private_tip_has_left = forms.BooleanField(label='PrivateのTipを残す', initial=False ,required=False)
    
    
class ReRegistrationForm(forms.Form):
    email = forms.EmailField(label='メールアドレス')

accounts/views.py
import textwrap

from allauth.account import views
from allauth.account.adapter import get_adapter
from allauth.account.models import EmailAddress
from allauth.account.signals import email_confirmed
from allauth.account.utils import (filter_users_by_email,
                                   send_email_confirmation)
from app.models import Notification, Tip
from app.utils import create_notification
from django.conf import settings
from django.contrib import messages
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.core.mail import BadHeaderError, EmailMessage
from django.dispatch import receiver
from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy
from django.views import View
from django.views.decorators.http import require_POST
from django.views.generic import TemplateView

from accounts.forms import ProfileForm, ReRegistrationForm, WithdrawalForm
from accounts.models import User


class ProfileView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user_data = User.objects.get(id=request.user.id)
        tips = Tip.objects.filter(created_by=user_data)
        private_tips_count = tips.filter(public_set=Tip.PRIVATE).count()
        public_tips_count = tips.filter(public_set=Tip.PUBLIC).count()

        return render(request, 'accounts/profile.html', {
            'user_data': user_data,
            'private_tips_count': private_tips_count,
            'public_tips_count': public_tips_count,
        })
        
        
class YourProfileView(View):
    def get(self, request, *args, **kwargs):
        if request.user.pk == self.kwargs.get('pk'):
            return redirect('accounts:profile')
        user_data = get_object_or_404(User, pk=self.kwargs.get('pk'))
        tips = Tip.objects.filter(created_by=user_data)
        public_tips_count = tips.filter(public_set=Tip.PUBLIC).count()
        
        return render(request, 'accounts/your_profile.html', {
            'user_data': user_data,
            'public_tips_count': public_tips_count,
        })
        

class ProfileEditView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        user_data = User.objects.get(id=request.user.id)
        form = ProfileForm(
            request.POST or None,
            initial = {
                'username': user_data.username,
                'icon': user_data.icon,
                'self_introduction': user_data.self_introduction
            }
        )
        
        return render(request, 'accounts/profile_edit.html', {
            'form': form,
        })
        
    def post(self, request, *args, **kwargs):
        user_data = User.objects.get(id=request.user.id)
        form = ProfileForm(request.POST or None, request.FILES or None, instance=user_data)

        if form.is_valid():
            user_data.username = form.cleaned_data.get('username')
            user_data.self_introduction = form.cleaned_data.get('self_introduction')
            if request.FILES:
                user_data.icon = request.FILES.get('icon')
            user_data.save()
            return redirect('accounts:profile')

        return render(request, 'accounts/profile_edit.html', {
            'form': form,
        })


class LoginView(views.LoginView):
    template_name = 'accounts/login.html'


@login_required
def logout_view(request):
    logout(request)
    return redirect('app:index')
    

class SignupView(views.SignupView):
    template_name = 'accounts/signup.html'


class PasswordChangeView(LoginRequiredMixin, views.PasswordChangeView):
    success_url = reverse_lazy('accounts:profile')


class PasswordSetView(LoginRequiredMixin, views.PasswordSetView):
    success_url = reverse_lazy('accounts:profile')


class WithdrawalView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        form = WithdrawalForm(request.POST or None)
        
        return render(request, 'accounts/withdrawal.html', {
            'form': form,
        })
        
    def post(self, request, *args, **kwargs):
        user_data = User.objects.get(id=request.user.id)
        form = WithdrawalForm(request.POST)

        if form.is_valid():
            private_tip_has_left = form.cleaned_data.get('private_tip_has_left')
            # 退会ユーザのデータ削除
            if not private_tip_has_left:
                # privatetipを全て削除
                Tip.objects.filter(created_by=user_data, public_set=Tip.PRIVATE).delete()
            # notificationを全削除
            Notification.objects.filter(to_user=user_data).delete()
            # emailaddressを削除
            EmailAddress.objects.filter(user=user_data).delete()
            # userのiconをNone、is_activateをfalseに更新
            user_data.icon = None
            user_data.is_active = False
            user_data.save()
            # 退会メールを送信
            name = user_data.username
            email = user_data.email
            subject = '[TipStock]退会手続き完了のお知らせ'
            contact = textwrap.dedent(f'''
                ※このメールはシステムからの自動返信です。

                {name} 様

                退会手続きを完了いたしました。
                この度はTipStockをご利用いただき誠にありがとうございました。
                本ユーザアカウントで再登録をご希望の場合は、
                サイト内のユーザ登録から「退会ユーザの再登録」を実施ください。
                
                TipStock
                https://www.tipstock.info/
                [お問い合わせページ]
                https://www.tipstock.info/contact/
                ''')
            to_list = [email]
            bcc_list = [settings.BCC_EMAIL]

            try:
                message = EmailMessage(subject=subject, body=contact,to=to_list, bcc=bcc_list)
                message.send()
            except BadHeaderError:
                # TODO この時点でログアウトしており、loginページredirectになる？
                return HttpResponse('無効なヘッダが検出されました。')

            # 退会完了ページに移動
            return redirect('accounts:withdrawal_done')

        return render(request, 'accounts/withdrawal.html', {
            'form': form,
        })


class WithdrawalDoneView(TemplateView):
    template_name = 'accounts/withdrawal_done.html'


class ReRegistrationView(View):
    def get(self, request, *args, **kwargs):
        form = ReRegistrationForm(request.POST or None)
        
        return render(request, 'accounts/reregistration.html', {
            'form': form,
        })
        
    def post(self, request, *args, **kwargs):
        form = ReRegistrationForm(request.POST or None)

        if form.is_valid():
            email = form.cleaned_data.get('email')
            # 入力したemailでuserのis_activeがfalseのuser(再登録対象者)を抽出
            user = filter_users_by_email(email, is_active=False)
            if user:
                # HACK verifyの判定のためemailaddressを取得しているが、
                    # send_email_confirmation内でも同じ処理でverifyの判定をしている（ただ、returnがないので判別はできない）。
                    # 自前で同様の関数を作成すれば2度読みは解消できるが、とりあえずは実行数も少ないので既存の関数をそのまま使用。
                try:
                    emailaddress = EmailAddress.objects.get_for_user(user[0], email)
                    # 通常userのis_activeはfalseでemailaddressのverifiedがtrueというケースはありえないが
                    # もしそのような状態になっている場合はverifiedをfalseにして再度メール認証を行い、userをactiveにする。
                    # (send_email_confirmation内でverifiedがTrueの場合は処理しないため)
                    if emailaddress.verified == True:
                        emailaddress.verified = False
                        emailaddress.save()
                except EmailAddress.DoesNotExist:
                    pass
                
                send_email_confirmation(request, user[0], email=email)
                adapter = get_adapter(request)
                return adapter.respond_email_verification_sent(request, user)

            form.add_error('email', '未登録、または有効なユーザのメールアドレスです。')
            return render(request, 'accounts/reregistration.html', {
                'form': form,
            })

        return render(request, 'accounts/reregistration.html', {
            'form': form,
        })


@receiver(email_confirmed)
def email_confirmed_(request, email_address, **kwargs):
    user = email_address.user
    if user.is_active == False:
        user.is_active = True
        user.save()


@login_required
def follow_user(request, pk):
    user = request.user
    if user.pk == pk:
        raise PermissionDenied('自身へのフォローはできません。')
    followed_user = get_object_or_404(User, pk=pk)
    follows = user.follows.all()
    #既にフォローしていればメッセージのみ送信
    if followed_user in follows:
        messages.info(request, 'フォロー済みです。')
    else:
        user.follows.add(followed_user)
        messages.success(request, 'フォローしました')
        create_notification(request, to_user=followed_user, category=Notification.FOLLOW)

    return redirect('accounts:your_profile', pk=pk)


@login_required
def unfollow_user(request, pk):
    user = request.user
    if user.pk == pk:
        raise PermissionDenied('自身へのフォロー解除はできません。')
    followed_user = get_object_or_404(User, pk=pk)
    follows = user.follows.all()
    #既にフォロー解除済みであればメッセージのみ送信
    if followed_user in follows:
        user.follows.remove(followed_user)
        messages.success(request, 'フォローを解除しました')
    else:
        messages.info(request, 'フォロー解除済みです。')

    return redirect('accounts:your_profile', pk=pk)


def follows(request, pk):
    user = get_object_or_404(User, pk=pk)
    
    path = request.path_info
    if 'follows' in path:
        # フォローを表示
        follows = user.follows.all().prefetch_related('created_tip')
        title = 'フォロー'
    else:
        # フォロワーを表示
        follows = user.followed_by.all().prefetch_related('created_tip')
        title = 'フォロワー'

    latest_tip = []
    public_tips_counts = []
    for user in follows:
        tips = Tip.objects.filter(public_set=Tip.PUBLIC, created_by=user).order_by('-updated_at')
        if tips.exists():

templates/accounts/follow.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% load access_list %}

{% block title %}{{ title }}
{% endblock %}

{% block content %}
    <h2 class="my-3 me-3">{{ title }}</h2>
    {% if not follows %}
        <p>{{ title }}はいません。</p>
    {% endif %}

    {% for user in follows %}
        <div class="card my-4" style="max-width: 800px;">
            <div class="row">
                <div class="col-3 col-md-2 px-0 d-flex align-items-center justify-content-center">
                    <img
                        src="
                        {% if user.icon %}
                            {{ user.icon.url }}
                        {% else %}
                            {% static 'accounts/img/noimage.png' %}
                        {% endif %}"
                        class="follow-icon">
                </div>
                <div class="col-9 col-md-10 px-0">
                    <div class="card-body follow-body">
                        <p class="card-text">
                            <a href="{% url 'accounts:your_profile' user.pk %}">
                                <strong>
                                    {% if user.is_active %}
                                        {{ user.username }}
                                    {% else %}
                                        Inactive User
                                    {% endif %}
                                </strong>
                            </a>
                            <br>
                            {% access_list public_tips_counts forloop.counter0 as tip_count %}
                            <span class="d-inline-block">投稿数(Public)：{{ tip_count }}&emsp;</span>
                            <span class="d-inline-block">フォロワー：{{ user.followed_by.count }}&emsp;フォロー：{{ user.follows.count }}</span>
                            {% if user.self_introduction %}<br>{{ user.self_introduction }}
                            {% endif %}
                            <br>
                            {% access_list latest_tip forloop.counter0 as tip %}
                            {% if tip %}
                                <a href="{% url 'app:tip_detail' tip.pk %}">最新Tip：{{ tip.title }}</a>
                                <br>
                                更新日：{{ tip.updated_at|naturaltime }}
                            {% else %}
                                Tipはありません。
                            {% endif %}
                        </p>
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

{% endblock %}

templates/accounts/lockout.html
{% extends "base.html" %}

{% block title %}アクセスロック{% endblock %}

{% block content %}

    <div class="card card-profile my-5 mx-auto">
        <div class="card-body">
            <div class="card-title auth-message-title">アクセスロック</div>
            <div class="auth-message-content">
                <p>ログイン試行回数が規定回数(5回)を超えたため、<br>
                    アクセスをロックしました。<br>
                    アクセスロックを解除するにはお問い合わせよりご連絡ください。</p>
            </div>
        </div>
    </div>

{% endblock %}

templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}プロフィール{% endblock %}

{% block content %}

    <div class="card card-profile my-5 mx-auto">
        <div class="card-body">
            <h5 class="card-title text-center">プロフィール</h5>
            <table class="profile_table mb-4">
                <tbody>
                    <tr>
                        <th class="header">ユーザ名</th>
                        <td class="data">{{ user_data.username }}</td>
                    </tr>
                    <tr>
                        <th class="header">メールアドレス</th>
                        <td class="data">{{ user_data.email }}</td>
                    </tr>
                    <tr>
                        <th class="header">アイコン</th>
                        <td class="data"><img
                            src="{% if user_data.icon %}{{ user_data.icon.url }}{% else %}{% static 'accounts/img/noimage.png' %}{% endif %}"
                            class="d-block mx-auto default-preview-img"></td>
                    </tr>
                    <tr>
                        <th class="header">自己紹介</th>
                        <td class="data">{{ user_data.self_introduction|linebreaks }}</td>
                    </tr>
                    <tr>
                        <th class="header">データ</th>
                        <td class="data">
                            <span style="display: inline-block;">投稿数：Private
                                {{ private_tips_count }}&emsp;Public
                                {{ public_tips_count }}&emsp;</span>
                            <span style="display: inline-block;">
                                フォロワー：<a href="{% url 'accounts:followers' user_data.pk %}">{{ user_data.followed_by.count }}</a>&emsp; フォロー：<a href="{% url 'accounts:follows' user_data.pk %}">{{ user_data.follows.count }}</a>
                            </span>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="mx-auto text-center">
                <a href="{% url 'accounts:profile_edit' %}" class="btn btn-custom btn-lg btn-warning btn-block">編集する</a>
                <a href="{% url 'account_change_password' %}" class="btn btn-custom btn-lg btn-danger btn-block">パスワード変更</a>
            </div>
        </div>
    </div>

{% endblock %}

templates/accounts/reregistration.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}ユーザ再登録{% endblock %}

{% block content %}

    <div class="card card-profile my-5 mx-auto">
        <div class="card-body">
            <div class="card-title auth-message-title">ユーザ再登録</div>
            <div class="auth-message-content">
                <p>退会済みのユーザを再登録するためには、本登録を実施する必要があります。<br>
                    メールアドレスを入力し送信ボタンをクリックしてください。<br>
                    本登録実施のためのメールが送信されます。</p>
            </div>
            <form method="POST" action="{% url 'accounts:reregistration' %}">
                {% csrf_token %}
                <table class="profile_table mb-4">
                    <tbody>
                        <tr>
                            <th class="header">{{ form.email.label }}</th>
                            <td class="data">
                                {% render_field form.email class="form-control" placeholder='' %}
                                {% for error in form.email.errors %}
                                    <p class="text-danger">{{ error }}</p>
                                {% endfor %}
                            </td>
                        </tr>
                    </tbody>
                </table>
                {# non_field_errorを表示 #}
                {% include 'form_alert.html' %}
                <div class="button mx-auto text-center my-2">
                    <button class="btn btn-custom btn-lg btn-primary btn-block" type="submit">メール送信</button>
                </div>
            </form>
        </div>
    </div>

{% endblock %}

templates/accounts/signup.html
{% extends "base.html" %}
{% load widget_tweaks %}
{% load static %}
{% load socialaccount %}

{% block extra_css%}
    <link rel="stylesheet" href="{% static 'accounts/css/bootstrap-social.css' %}">
{% endblock %}

{% block title %}サインアップ{% endblock %}

{% block content %}

    <div class="card card-auth my-5 mx-auto">
        <div class="card-body pb-3">
            <h5 class="card-title text-center">サインアップ</h5>
            <form class="form-auth" method="post">
                {% csrf_token %}
                <div class="form-label-group">
                    {% render_field form.username class="form-control" placeholder='ユーザ名' %}
                    {% for error in form.username.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
                <div class="form-label-group">
                    {% render_field form.email class="form-control" placeholder='メールアドレス' %}
                    {% for error in form.email.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
                <div class="form-label-group">
                    {% render_field form.password1 class="form-control" placeholder='パスワード' %}
                    {% for error in form.password1.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
                <div class="form-label-group">
                    {% render_field form.password2 class="form-control" placeholder='パスワード(確認)' %}
                    {% for error in form.password2.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                </div>
                {# non_field_errorを表示 #}
                {% include 'form_alert.html' %}
                <p><small>サインアップすると仮登録されます。<br>入力したメールアドレスに本登録用のメールを送信しますので、引き続き本登録を実施してください。</small></p>
                <div class="button mx-auto text-center">
                    <button class="btn btn-custom btn-lg btn-primary btn-block" type="submit">サインアップ</button>
                </div>
            </form>
        </div>
        <div class="mx-auto mb-1 text-center">
            <p class="mb-1">ソーシャルアカウントでサインアップ</p>
            <p><small>（GitHubは仮登録(メール認証が必要)となります）</small></p>
        </div>
        <div class="button-social mx-auto mb-2">
            <a href="{% provider_login_url 'google' %}" class="btn btn-custom btn-social btn-google"><span class="fab fa-google"></span>Googleでサインアップ</a>
        </div>
        <div class="button-social mx-auto  mb-2">
            <a href="{% provider_login_url 'github' %}" class="btn btn-custom btn-block btn-social btn-github"><span class="fab fa-github"></span>GitHubでサインアップ</a>
        </div>
        <p class="mb-2 text-center">既にアカウントを持っている方は<br><a href="{{ login_url }}">ここからログイン</a>してください.</p>
        <p class="text-center">退会ユーザの再登録は<a href="{% url 'accounts:reregistration' %}">こちら</a></p>
    </div>

{% endblock %}

templates/accounts/withdrawal.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}ユーザ退会{% endblock %}

{% block content %}

    <div class="card card-profile my-5 mx-auto">
        <div class="card-body">
            <div class="card-title auth-message-title">ユーザ退会</div>
            <div class="auth-message-content mb-5">
                <p>本ページはユーザ退会のページとなります。<br>
                    下記の注意事項をご確認の上、退会する場合は退会ボタンをクリックしてください。</p>
                
                <p class="fw-bold">退会における注意事項</p>
                <p>退会処理におけるデータの削除処理については以下の通りとなります。</p>
                <table class="table table-sm table-bordered">
                    <thead>
                        <tr class="table-light">
                            <th scope="col">削除しない<br>(全体共有データ)</th>
                            <th scope="col">削除する<br>(個人データ)</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>公開範囲がPublicのTip</td>
                            <td>公開範囲がPrivateのTip</td>
                        </tr>
                        <tr>
                            <td>コメント</td>
                            <td>お知らせ</td>
                        </tr>
                        <tr>
                            <td>お気に入り登録</td>
                            <td>ユーザアイコン</td>
                        </tr>
                    </tbody>
                </table>
                <p class="text-start">
                    「PublicのTip」については本サービスの大きな資産である為、基本的には残していただきたいと考えております。
                    ただし、どうしても削除したいTipがある場合は個別に削除していただいてから退会処理を実施してください。
                </p>
                <p class="text-start">
                    「PrivateのTip」については他人に見せないという観点から削除することにしておりますが、
                    以下の「PrivateのTipを残す」にチェックを入れて処理を実行していただくと削除いたしません。
                    退会処理を行うとユーザアカウントが無効となりますが、登録時のメールアドレスで再登録を実施することで
                    削除しなかったデータについては退会時の状態を引き継いだ形で始められるため、残すことも可能としております。
                </p>
                <p class="text-start">
                    「コメント」「お気に入り登録」は削除しない対象ですが、PrivateのTipを削除するとした場合は紐づく「コメント」「お気に入り登録」のデータもあわせて削除いたします。<br>
                    （通常PrivateのTipは「コメント」「お気に入り登録」は不可ですが、Publicにしていた期間がある場合はデータが存在するケースがあります。）
                </p>
            </div>
            <div class="text-center">
                <form method="POST" action="{% url 'accounts:withdrawal' %}" class="d-inline" id="withdrawal-form">
                    {% csrf_token %}
                    {{ form.private_tip_has_left }}
                    {{ form.private_tip_has_left.label }}
                    {% for error in form.private_tip_has_left.errors %}
                        <p class="text-danger">{{ error }}</p>
                    {% endfor %}
                    <div class="my-3">
                        <button class="btn btn-custom btn-lg btn-danger me-3" type="button" id="withdrawal-button">退会</button>
                        <a
                        href="javascript:void(0);"
                        onclick="window.history.back();"
                        class="btn btn-custom  btn-lg btn-outline-dark">戻る</a>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock %}

{% block extra_js %}
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script>
        $(function () {
            // 退会ボタンクリック時のダイアログ表示
            $("#withdrawal-button").click(function () {
                swal({
                    title: "本当に退会してもよろしいですか？",
                    text: "「PrivateのTipを残す」のチェックは忘れていませんか？",
                    icon: 'warning',
                    buttons: {
                        yes: "退会する",
                        cancel: "キャンセル",
                    },
                })
                .then((value) => {
                    switch (value) {
                    
                        case "yes":
                            $('#withdrawal-form').submit();
                            break;
                    
                        default:
                            break;
                    }
                });
            })
        });
    </script>

{% endblock %}

templates/accounts/withdrawal_done.html
{% extends "base.html" %}

{% block title %}退会処理完了{% endblock %}

{% block content %}

    <div class="card card-profile my-5 mx-auto">
        <div class="card-body">
            <div class="card-title auth-message-title">ユーザ退会処理の完了</div>
            <div class="auth-message-content">
                <p class="mb-2">
                    ユーザの退会処理が完了しました。<br>
                    登録しているメールアドレス宛に退会完了メールを送付しております。<br>
                    この度はTikStockをご利用いただき誠にありがとうございました。
                </p>
            </div>
        </div>
    </div>

{% endblock %}

templates/accounts/your_profile.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ user_data.username }}さんのプロフィール{% endblock %}

{% block content %}

    <div class="card card-profile my-5 mx-auto">
        <div class="card-body">
            <h5 class="card-title text-center">プロフィール</h5>
            <table class="profile_table mb-4">
                <tbody>
                    <tr>
                        <th class="header">ユーザ名</th>
                        <td class="data">{{ user_data.username }}</td>
                    </tr>
                    <tr>
                        <th class="header">アイコン</th>
                        <td class="data"><img
                            src="{% if user_data.icon %}{{ user_data.icon.url }}{% else %}{% static 'accounts/img/noimage.png' %}{% endif %}"
                            class="d-block mx-auto default-preview-img"></td>
                    </tr>
                    <tr>
                        <th class="header">自己紹介</th>
                        <td class="data">{{ user_data.self_introduction|linebreaks }}</td>
                    </tr>
                    <tr>
                        <th class="header">データ</th>
                        <td class="data">
                            <span style="display: inline-block;">投稿数(Public)：<a href="{% url 'app:usertip' user_data.id %}">{{ public_tips_count }}</a>&emsp;</span>
                            <span style="display: inline-block;">
                                フォロワー：<a href="{% url 'accounts:followers' user_data.pk %}">{{ user_data.followed_by.count }}</a>&emsp; フォロー：<a href="{% url 'accounts:follows' user_data.pk %}">{{ user_data.follows.count }}</a>
                            </span>
                        </td>
                    </tr>
                </tbody>
            </table>
            <div class="mx-auto text-center">
                <a href="{% url 'app:usertip' user_data.id %}" class="btn btn-custom btn-lg btn-warning btn-block">Tips</a>
                {% if user_data in request.user.follows.all %}
                    <a href="{% url 'accounts:unfollow_user' user_data.pk %}" class="btn btn-custom btn-lg btn-danger">フォローを外す</a>
                {% else %}
                    <a href="{% url 'accounts:follow_user' user_data.pk %}" class="btn btn-custom btn-lg btn-success">フォローする</a>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}