accounts/urls.py
from django.urls import path

from accounts import views

app_name = 'accounts'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('profile/edit/', views.ProfileEditView.as_view(), name='profile_edit'),
    path('your_profile/<int:pk>/', views.YourProfileView.as_view(), name='your_profile'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path("password/set/", views.PasswordSetView.as_view(), name="account_set_password"),
    path("password/change/", views.PasswordChangeView.as_view(), name="account_change_password"),
    path("withdrawal/", views.WithdrawalView.as_view(), name="withdrawal"),
    path("withdrawal_done/", views.WithdrawalDoneView.as_view(), name="withdrawal_done"),
    path("reregistration/", views.ReRegistrationView.as_view(), name="reregistration"),
    path('follow_user/<int:pk>/', views.follow_user, name='follow_user'),
    path('unfollow_user/<int:pk>/', views.unfollow_user, name='unfollow_user'),
    path('followers/<int:pk>/', views.follows, name='followers'),
    path('follows/<int:pk>/', views.follows, name='follows'),
]

app/urls.py
from django.urls import path

from app import views

app_name = 'app'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('tip_create/', views.TipCreateView.as_view(), name='tip_create'),
    path('tip_detail/<int:pk>/', views.TipDetailView.as_view(), name='tip_detail'),
    path('tip_update/<int:pk>/', views.TipUpdateView.as_view(), name='tip_update'),
    path('tip_delete/<int:pk>/', views.TipDeleteView.as_view(), name='tip_delete'),
    path('tip_list/', views.TipMyListView.as_view(), name='tip_list'),
    path('tip_public_list/', views.TipPublicListView.as_view(), name='tip_public_list'),
    path('add_comment/<int:pk>/', views.add_comment, name='add_comment'),
    path('delete_comment/<int:pk>/<int:comment_no>/', views.delete_comment, name='delete_comment'),
    path('add_like/<int:pk>/', views.add_like, name='add_like'),
    path('delete_like/<int:pk>/', views.delete_like, name='delete_like'),
    path('contact/', views.ContactView.as_view(), name='contact'),
    path('thanks/', views.ThanksView.as_view(), name='thanks'),
    path('notifications/', views.notifications, name='notifications'),
    path('terms/', views.TermsView.as_view(), name='terms'),
    path('policy/', views.PolicyView.as_view(), name='policy'),
    path('usertip/<int:id>/', views.UserTipView.as_view(), name='usertip'),
]

templates/503.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>サイトメンテナンス中 - TipStock</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
        <script defer="defer" src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    </head>
    <body>
        <section class="section">
            <div class="container">
                <h1 class="title">サイトのメンテナンス中です...</h1>
                <span class="icon has-text-info is-large">
                    <i class="fas fa-wrench fa-3x fa-spin"></i>
                </span>
            </div>
        </section>
    </body>
</html>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="ja">
    <head>
        <!-- Global site tag (gtag.js) - Google Analytics -->
        <script async="async" src="https://www.googletagmanager.com/gtag/js?id=G-94BLZWSY0R"></script>
        <script>
            window.dataLayer = window.dataLayer || [];
            function gtag() {
                dataLayer.push(arguments);
            }
            gtag('js', new Date());

            gtag('config', 'G-94BLZWSY0R');
        </script>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="{% static 'app/img/favicon.ico' %}">
        <link rel="apple-touch-icon" href="{% static 'app/img/apple-touch-icon.png' %}">
        <link rel="icon" type="image/png" href="{% static 'app/img/android-chrome-192x192.png' %}">
        <link
            rel="stylesheet"
            href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css"
            integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w=="
            crossorigin="anonymous"
            referrerpolicy="no-referrer"/>
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
            crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'app/css/style.css' %}">
        {% block extra_css%}{% endblock %}
        <title>
            {% block title %}TipStock{% endblock %}
        </title>
        {% block meta %}
            <meta name="twitter:card" content="summary" />
            <meta name="twitter:site" content="@yamana117" />
            <meta property="og:url" content="https://www.tipstock.info/" />
            <meta property="og:title" content="TipStock" />
            <meta property="og:description" content="プログラムコードをメインにしたTipの登録サイト" />
            <meta property="og:image" content="{% static 'app/img/android-chrome-192x192.png' %}" />
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container-fluid">
                <a href="/" class="navbar-brand">
                    <img
                        src="{% static 'app/img/android-chrome-192x192.png' %}"
                        alt=""
                        width="32"
                        height="32"
                        class="d-inline-block align-top">
                    TipStock
                </a>
                <button
                    class="navbar-toggler"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#navbarNav"
                    aria-controls="navbarNav"
                    aria-expanded="false">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item dropdown">
                            <a
                                class="nav-link dropdown-toggle"
                                href="#"
                                id="navbarDropdown-home"
                                role="button"
                                data-bs-toggle="dropdown"
                                aria-expanded="false">
                                ホーム
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdown-home">
                                <li>
                                    <a class="dropdown-item" href="/">ホーム</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'app:terms' %}">利用規約</a>
                                </li>
                                <li>
                                    <a class="dropdown-item" href="{% url 'app:policy' %}">プライバシーポリシー</a>
                                </li>
                            </ul>
                        </li>
                        {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a href="{% url 'app:tip_create' %}" class="nav-link">Tip Form</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'app:tip_list' %}" class="nav-link">My Tips</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a href="{% url 'app:tip_public_list' %}" class="nav-link">Public Tips</a>
                        </li>
                        {% if request.user.is_authenticated %}
                            <li class="nav-item">
                                <a href="{% url 'app:notifications' %}" class="nav-link">お知らせ ({{ notifications_count }})</a>
                            </li>
                            <li class="nav-item dropdown">
                                <a
                                    class="nav-link dropdown-toggle"
                                    href="#"
                                    id="navbarDropdown-user"
                                    role="button"
                                    data-bs-toggle="dropdown"
                                    aria-expanded="false">
                                    ユーザ
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="navbarDropdown-user">
                                    <li>
                                        <a class="dropdown-item" href="{% url 'accounts:profile' %}">プロフィール</a>
                                    </li>
                                    <li>
                                        <a class="dropdown-item" href="{% url 'accounts:withdrawal' %}">退会</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'accounts:logout' %}" class="nav-link">ログアウト</a>
                            </li>
                        {% else %}
                            <li class="nav-item">
                                <a href="{% url 'accounts:signup' %}" class="nav-link">ユーザ登録</a>
                            </li>
                            <li class="nav-item">
                                <a href="{% url 'accounts:login' %}" class="nav-link">ログイン</a>
                            </li>
                        {% endif %}
                        <li class="nav-item">
                            <a href="{% url 'app:contact' %}" class="nav-link">お問い合わせ</a>
                        </li>
                        <li class="nav-item twitter-icon">
                            <a href="https://twitter.com/yamana117117" target="_blank" rel="noopener">
                                <i class="fab fa-twitter fa-lg rounded btn-dark"></i>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

        <main>
            <div class="container">
                {% if messages %}
                    <br>
                    {% for message in messages %}
                        <div
                            class="alert{% if message.tags %} alert-{{ message.tags }}{% endif %} alert-dismissible fade show"
                            role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}
                {% block content %}{% endblock %}
            </div>
        </main>

        <footer class="py-2 bg-dark">
            <p class="m-0 text-center text-white copyright">Copyright &copy; TipStock 2021</p>
        </footer>

        <script
            src="https://code.jquery.com/jquery-3.6.0.slim.min.js"
            integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI="
            crossorigin="anonymous"></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
            crossorigin="anonymous"></script>

        {% block extra_js %}{% endblock %}
    </body>
</html>

templates/form_alert.html
{% if form.non_field_errors %}
    <div class="my-3">
        {% for non_field_error in form.non_field_errors %}
            <p class="text-danger">{{ non_field_error }}</p>
        {% endfor %}
    </div>
{% endif %}